language: node_js
install: npm install -g gitbook-cli
before_script: gitbook install
node_js:
- '0.10'
script: gitbook build
after_success:
- bash deploy.sh
env:
  global:
    secure: sJiljw8tHgqIz9fIWDi3ixDOQc2VvyU1zO9TnoNF/3N7VbnFZPQTBew/9BIvNk8ZPuD+YpfsHMan1pTb16EYq02s+gW+9ji4yo2XNhtYiNLKMyTrZYkGdVni/blF6Ed/BKwiqAOm/3CuT6QGj4XGsYhZ01IFRPmcrLi3FiQSoXVN3EvcT9+GKns4QzOawftv5RnMiOPmOKlTMQDSukBDwFmdXjUU7NgfdB+4gS/J+7wZBiy27M5XQpYWWNrfN/RLIvaeLRjRaAbs/mQSg5h5jl2wtS7of5/nJq6IFTWFYKzuXo8gfdjT7Kbn9EjHvw4j8Y/FcLrsE9DzEYC1c8nfF1SQjgffpoSqdHW8Ex6G7X33eopac/RBeWDzm5gxHQXSk1Z5R0iY2NpgHLTEAkvVHP4Lso6/EFmwf+5oywz8JBLAtgU1KbwO6hTZ6NeNLXZTS+LBEx3P1MWMcDEDTKH43SpXLVHgdiCF3L7Cdr5c57+4WKtGnkky2b5mFShoUM5ifhP1OHHKXJtwP2cDQDVPCwDbd3RywI6BRq7qJIuGSEEz5f59gwLFAOW/vcltsTma4RSl3RPC6zEENJ6Pp70qwxugpEHaXyN1dkA4Io/NeH+PqKCsYMWP8FLWoMvBoBxb2tCOjHVeXr5wbzkM+S/W6X33sITqpKb5OUdtFiBSZ20=
